"""empty message

Revision ID: 048464e496b0
Revises: 09f89d4dad7f
Create Date: 2018-04-18 12:08:03.108420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048464e496b0'
down_revision = '09f89d4dad7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_code', sa.BIGINT(), nullable=False))
    op.create_unique_constraint(None, 'books', ['book_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'book_code')
    # ### end Alembic commands ###
