"""empty message

Revision ID: 09f89d4dad7f
Revises: 10490bf432ee
Create Date: 2018-04-18 12:07:29.229990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f89d4dad7f'
down_revision = '10490bf432ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_book_code_key', 'books', type_='unique')
    op.drop_column('books', 'book_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_unique_constraint('books_book_code_key', 'books', ['book_code'])
    # ### end Alembic commands ###
