"""empty message

Revision ID: 10490bf432ee
Revises: a8a6658c7973
Create Date: 2018-04-18 12:06:02.156078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10490bf432ee'
down_revision = 'a8a6658c7973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ddc_code', sa.String(length=30), nullable=True))
    op.alter_column('books', 'book_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('books', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'available'::character varying"))
    op.create_unique_constraint(None, 'books', ['book_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'available'::character varying"))
    op.alter_column('books', 'book_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('books', 'ddc_code')
    # ### end Alembic commands ###
