"""empty message

Revision ID: 79d602395914
Revises: ce3f8fb885cb
Create Date: 2018-04-27 15:49:30.774744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d602395914'
down_revision = 'ce3f8fb885cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_code', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('ddc_code', sa.String(length=30), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('genre', sa.Enum('Fiction', 'Non_fiction', name='genre'), nullable=True),
    sa.Column('sub_genre', sa.String(length=70), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('acc_status', sa.String(length=40), nullable=True),
    sa.Column('borrowed_books', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
