"""empty message

Revision ID: ce3f8fb885cb
Revises: 048464e496b0
Create Date: 2018-04-25 18:43:43.807086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3f8fb885cb'
down_revision = '048464e496b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('borrowed_books', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'borrowed_books')
    # ### end Alembic commands ###
