"""empty message

Revision ID: f46fb4ef812f
Revises: 
Create Date: 2018-04-05 12:41:14.811752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46fb4ef812f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('book_code', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.Column('synopsis', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('subgenre', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
